### ISSUE TITLE
best project of all time~

### ISSUE THREAD

**Issue by J-ZhengLi** [blyxyas/cat-ascii-faces#1]
Can I suggest some more variations lol 😆 

ฅ/ᐠ˶>ﻌ<˶ᐟ\ฅ

ฅ/ᐠ˶òܫó˶ᐟ\ฅ

ฅ(=^Õ ‸ Õ^=)ฅ

/ᐠﹷ ‸ ﹷ ᐟ\Ⳋ

**Comment by blyxyas** [comment]
I'll add them hehe, if you want to make a PR, I'll accept it (if not, wait a bit meow meow :3)
